server:
    port: 9001
    
spring:
    datasource:
        name: bbs
        url: jdbc:mysql://localhost:3306/tabledata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    
    redis:
        database: 1 #索引（默认为0）
        host: 127.0.0.1 #地址
        port: 6379 #端口号
        #password:  #连接密码（默认空）
        pool:
          max-idle: 8 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
          max-active: 8 #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        #sentinel:
          #master: mymaster # 哨兵监听的Redis server的名称
          #nodes:
            #127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579 #哨兵的配置列表
        timeout: 5000 #连接超时时间（毫秒）
        
mybatis:
    mapper-locations: classpath:com/example/demo/mapper/*.xml
    type-aliases-package: com.example.demo.pojo

mapper:
    mappers: com.example.demo.mapper
    not-empty: false
    identity: MYSQL

logging:
  level:
    com:
      example:
        demo:
            mapper: debug
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count= countSql
    returnPageInfo: check
    